EG97-4 Schema y ruta de creacion de review
NemoruFran/EGulfProjectNuclio-Backend pull request #5
Opened 2021-06-14 19:07 UTC by FedericoVelez25

2021-06-16 17:47 UTC, NemoruFran commented on src/reviews/model/reviews.model.js
> +    userId: [{
Si es el creador del producto yo le llamaria ProductOwnedId

2021-06-16 17:47 UTC, NemoruFran commented on src/reviews/model/reviews.model.js
> +    productId: String,
Esto de aquí debería ser una relación esquemática como en el caso de usuarios

2021-06-16 17:47 UTC, NemoruFran commented on src/reviews/reviews.model.js
> +    date: { type: Date, default: Date.now },
Se podría llamar creation date

2021-06-16 17:47 UTC, NemoruFran commented on src/reviews/reviews.model.js
> +    return reviewCreated;
En vez de poner el return de la variable reviewCreated se podría poner el await directamente como return

2021-06-16 17:47 UTC, NemoruFran commented on src/reviews/reviews.router.js
> +
Falta otro router que reciba el id de review. Algo así como:


```suggestion
router.route('/reviews/:reviewid')
    .get(reviewsController.getReview)
    .delete(reviewsController.removeReview)
```

2021-06-16 17:47 UTC, NemoruFran commented on src/reviews/reviews.router.js
> +    .get(reviewsController.getReview)
Borrar esta línea si se añade el router de más abajo

2021-06-16 17:47 UTC, NemoruFran commented on src/reviews/reviews.router.js
> +    .delete(reviewsController.removeReview)
Para borrar una review es mejor el review id, esto mejor meterlo dentro del router de más abajo

2021-06-16 17:47 UTC, NemoruFran commented on src/reviews/reviews.controller.js
> +     const review = await reviewModel.get(req.body.id);
Cambiar body.id por params.reviewid:
```suggestion
     const review = await reviewModel.get(req.params.reviewid);
```

2021-06-16 17:47 UTC, NemoruFran commented on src/reviews/reviews.controller.js
> +     const review = await pinModel.remove(req.params.id);
nice copiapega
```suggestion
     const review = await reviewModel.remove(req.params.reviewid);
```

2021-06-16 17:47 UTC, NemoruFran commented on src/reviews/reviews.controller.js
> +     const id = req.params.id;
```suggestion
     const id = req.params.reviewid;
```

2021-06-16 17:47 UTC, NemoruFran commented on src/reviews/reviews.controller.js
> +const getAllReviews = async (req, res) => {
dividir en getallreviews por productid y getallreviews por userid

2021-06-17 18:16 UTC, angelbt91 requested changes
Te he dejado comentarios para revisar :)

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.model.js
> +    productOwnerId: [{
Sugerencia: qué tal "sellerUserId"?

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.model.js
> +    userReviewerId: [{
Sugerencia: qué tal "buyerUserId"?

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.model.js
> +const ReviewModel = mongoose.model('review', ReviewSchema, );
` const ReviewModel = mongoose.model('review', ReviewSchema);`
(mejor quitar la coma del final de los argumentos de la función)

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.model.js
> +}; */
Si no vamos a permitir hacer updates o getAll, mejor borrar los comentarios para tener un fichero limpito :)

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.model.js
> +getAll, */
Misma cosa que el comentario anterior

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.controller.js
> +};
Esta función no elimina reviews, como cabría esperar por el nombre.

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.controller.js
> +};
Para "pedir" una review, con tan solo el parámetro ID es suficiente

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.controller.js
> + */
Esto tiene mejor pinta que el siguiente `getReview()`!

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.router.js
> +    .delete(reviewsController.removeReview)
> Para borrar una review es mejor el review id, esto mejor meterlo dentro del router de más abajo

A priori, aquí, el método `removeReview()` de `reviewsController` lo estamos llamando en los DELETE a `/reviews/:reviewId`. ¿No es eso lo que esperas ver?

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.controller.js
> +};
Para recoger las reviews de un producto, tiene mejor pinta la función comentada que la de debajo. Repasa el flujo completo desde que el router recoge esta llamada hasta que llega al model, pasando por el controller, para poder visualizar qué está ocurriendo.

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.controller.js
> +};
Para recoger las reviews de un producto, tiene mejor pinta la función comentada que la de debajo. Repasa el flujo completo desde que el router recoge esta llamada hasta que llega al model, pasando por el controller, para poder visualizar qué está ocurriendo.

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.controller.js
> +};
Para recoger las reviews de un producto, tiene mejor pinta la función comentada que la de debajo. Repasa el flujo completo desde que el router recoge esta llamada hasta que llega al model, pasando por el controller, para poder visualizar qué está ocurriendo.

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.controller.js
> +};
Por un lado, cuando creaste la ruta para crear review, en la URL pides el productId, pero no el userId, así que no puedes sacarlo de params.
Por el otro, no estás recogiendo el productId de los parámetros para añadirlo a la review antes de guardar.

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.controller.js
> +};
Ah, ya veo, en el router usas dos veces esta función, tanto en la línea 8 como en la 17. Para la 17 no aplica la primera indicación que te menciono, no obstante, si las reviews van siempre ligadas a los productos, la 17 no debería existir.

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.router.js
> +    .post(reviewsController.createReview)
Como hablado en un comentario en el controller, esta llamada a createReview está duplicada, y probablemente tenga sentido mantener la primera en lugar de esta

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.controller.js
> +     res.status(201).json(reviews)
Para conseguir las reviews de un usuario, solo necesitas saber qué usuario (es decir, el parámetro de userId)

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.controller.js
> +}; */
Si no vamos a permitir actualizar reviews, mejor quitar estos comentarios y mantener el código limpio :)

2021-06-17 18:16 UTC, angelbt91 commented on src/reviews/reviews.controller.js
> +/* controller */
Estas dos líneas sobran, ¿no?

2021-06-21 17:43 UTC, merged