Eg97 1
NemoruFran/EGulfProjectNuclio-Backend pull request #8
Opened 2021-06-17 12:23 UTC by luisabc132

Hola he agregado la parte auth y modificado nun problema de naming en el controlador de user

2021-06-17 17:27 UTC, angelbt91 requested changes
To do:
- Revisar el modelo de user, parece que hay una referencia equivocada en bids
- Revisar otros detalles menores (ver comentarios)

2021-06-17 17:27 UTC, angelbt91 commented on src/auth/auth.controller.js
> +        console.log("entre a comparar")
Idealmente, los logueos para el debugging los quitamos antes de mergear ramas

2021-06-17 17:27 UTC, angelbt91 commented on src/auth/auth.controller.js
> +    return res.status(400).json('Not  found')
Idealmente, no avisamos al usuario si el problema está en que el user no existe, o que el password es incorrecto. Con esta información le facilitamos a alguien malintencionado el robo de datos.

2021-06-17 17:27 UTC, angelbt91 commented on src/users/users.model.js
>          ref:"ratings"
bids hace referencia a ratings?

2021-06-17 17:27 UTC, angelbt91 commented on src/users/users.router.js
> +    console.log(tokenWithBearer);
Recordar quitar los logs de debugueo antes de pedir merge

2021-06-18 06:54 UTC, luisabc132 commented on src/auth/auth.controller.js
> +        console.log("entre a comparar")
ok resuelto

2021-06-18 06:54 UTC, luisabc132 commented on src/auth/auth.controller.js
> +    return res.status(400).json('Not  found')
Toda la razón

2021-06-18 06:54 UTC, luisabc132 commented on src/users/users.router.js
> +    console.log(tokenWithBearer);
ok

2021-06-18 08:23 UTC, closed without merging